const info = {
    text: "30.000 square meters of explorable digital space divided into 6 action packed floors with the arena at its focal point. Every floor will have its own unique amenities, attractions, functionalities and experiences. The arena will boast a virtual reality space for real world celebrity concerts, fighting events and for various types of performances. We plan to unlock new revenue streams by acquiring volumetric video capture technology and further monetizing already existing events, offering a brand-new way to directly connect with their fanbase.",
    text2:
      "A state of the art facility that provides an array of  interactive virtual reality health and fitness movement  mini-games  This is the first Move to Earn game in VR, where players   can stay fit and get paid   . With our own twist to the very popular play to earn  model “train to earn” promises to keep users coming back  for more.  A wide range of fully immersive fitness studios connecting  celebrities, world renowned athletes and trainers to users  while offering courses & className es online in VR. Enjoy  stretching, yoga, fitness movements, refloxology, and   other exercise activities in group or private sessions   from the comfort of your own home.MOVE TO EARN APPS  Galaxians will be able to reap rewards by participating in  VR mini games found in the exclusive spaces of their   favorite move to earn apps placed strategically within the    Galaxy gym. These include big names such as Menzy,  Dotmoovs & Fitevo.",
    text3:
      " Standing alongside the arena and the gym, the Galaxy Tower   is a marvel on its own. While the top floor is reserved for our Sky lounge social nightclub & celestial casino, the rest of the tower will include a collection of 20,000  unique NFT units, divided into luxury suites, lounges,   office spaces, and digital real estate. Each of these  areas will be uniquely designed by our creative team, who will build each space with one-of-a-kind styles and  exclusive decorative pieces in line with its respective  use case.",
  };
  
  export default info;
  